services:
  postgres:
    image: 'postgres:latest'
    environment:
      # Todo: store secrets somewhere else and get them from environment
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - 'pg_data:/var/lib/postgresql'
    ports:
      # Todo: change to use only internal network later
      - '5432:5432'
  # Todo: add service for backend

  # Todo: add service for frontend

  # Todo: add service for reverse proxy (maybe)
volumes:
  pg_data: